### ISSUE TITLE
please enter a name bug

### ISSUE THREAD

**Issue by montao** [montao/montaoproject#32]
![plaese-enter a-name](https://cloud.githubusercontent.com/assets/51189/25120997/6eee7e1a-2420-11e7-81ac-f3d7c5eb32aa.png)

**Comment by sayedrafeeq** [comment]
Hi Niklas, I have fixed the "please enter a name bug" of customer care form ( name input ).
We need to edit 'custom.js' file and change the line number 68.

### `type   : 'regExp[/^[a-z0-9_-]{4,16}$/]',`    to    `type   : 'empty',`

**Just change type value empty:** 
###  type   : 'empty',
